"""Domain layer package - pure domain entities and rules."""

from src.domain.entities import (
    TenantId,
    DocumentId,
    ChunkId,
    StoredFile,
    ExtractedText,
    Chunk,
    ChunkSpec,
    Answer,
    UploadResult,
    DocumentStatus,
    ChatSession,
    ChatTurn,
)
from src.domain.errors import (
    DomainError,
    DocumentNotFoundError,
    DocumentAlreadyExistsError,
    DocumentProcessingError,
    InvalidFileError,
    FileTooLargeError,
    UnsupportedFileTypeError,
    TextExtractionError,
    NoTextExtractedError,
    SearchError,
    EmbeddingError,
    LLMError,
    LLMRateLimitError,
    AuthenticationError,
    AuthorizationError,
    TenantAccessError,
)

__all__ = [
    # Entities
    "TenantId",
    "DocumentId",
    "ChunkId",
    "StoredFile",
    "ExtractedText",
    "Chunk",
    "ChunkSpec",
    "Answer",
    "UploadResult",
    "DocumentStatus",
    "ChatSession",
    "ChatTurn",
    # Errors
    "DomainError",
    "DocumentNotFoundError",
    "DocumentAlreadyExistsError",
    "DocumentProcessingError",
    "InvalidFileError",
    "FileTooLargeError",
    "UnsupportedFileTypeError",
    "TextExtractionError",
    "NoTextExtractedError",
    "SearchError",
    "EmbeddingError",
    "LLMError",
    "LLMRateLimitError",
    "AuthenticationError",
    "AuthorizationError",
    "TenantAccessError",
]
