name: Portfolio Project
description: Define a shippable, portfolio-worthy project (Week 4, 8, 12 milestones)
title: "Project: [Name]"
labels: ["portfolio"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What real-world problem does this solve?
      placeholder: "Current RAG systems hallucinate on legal documents due to poor context retrieval..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Technical Solution
      description: Architecture and key technologies.
      placeholder: "Hybrid Search (BM25 + HNSW) with Cohere Re-ranking..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Definition of Done
      options:
        - label: "Codebase clean & modular"
        - label: "Unit tests passing (>80% coverage)"
        - label: "README with architecture diagram"
        - label: "Video Demo (Loom/YouTube) embedded"
        - label: "Live Deployment (Streamlit/FastAPI)"

  - type: textarea
    id: metrics
    attributes:
      label: Success Metrics
      description: Quantifiable results.
      placeholder: "Latency < 200ms, Retrieval Recall@10 > 90%..."
