name: Weekly Sprint
description: Plan and track a single week of AI mastery
title: "Week [N]: [Theme/Concept]"
labels: ["sprint"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Sprint Goal
      description: What is the SINGLE main outcome? (e.g., "Implement Transformer from scratch")
      placeholder: "Build and verify a multi-head attention block."
    validations:
      required: true

  - type: checkboxes
    id: deep_work
    attributes:
      label: Deep Work Sessions (3 Days)
      description: Track your focused learning blocks.
      options:
        - label: "Day 1: Theory & Math (4h) - [Paper/Reference]"
        - label: "Day 2: Core Implementation (4h) - [Code]"
        - label: "Day 3: Optimization & Tests (4h) - [Refactor]"

  - type: checkboxes
    id: application
    attributes:
      label: Application Sessions (2 Days)
      description: Apply what you learned to a real project.
      options:
        - label: "Day 4: Integration / App Feature"
        - label: "Day 5: Deployment / Documentation / Demo"

  - type: textarea
    id: deliverables
    attributes:
      label: Shippable Artifacts
      description: What will you commit to the repo?
      placeholder: "- [ ] src/llm/attention.py\n- [ ] notebooks/week07_transformer.ipynb\n- [ ] README update with benchmarks"
    validations:
      required: true

  - type: textarea
    id: reflection
    attributes:
      label: Learning Log
      description: Key takeaways, pitfalls, and 'Aha!' moments.
      placeholder: "Realized why scaling by sqrt(d_k) is crucial..."
