"""
Utilities Module for AI-Mastery-2026
=====================================

Shared utilities used across all modules.

Submodules:
-----------
- logging: Unified logging configuration
- errors: Unified error handling
- config: Configuration management
- types: Shared type definitions

Usage:
------
    from src.utils import get_logger, get_config, AIMasteryError
    from src.utils.types import DocumentProtocol, EmbeddingVector

    logger = get_logger(__name__)
    config = get_config()
"""

from src.utils.config import (APIConfig, CacheConfig, Config, DatabaseConfig,
                              EmbeddingConfig, LLMConfig, MonitoringConfig,
                              RAGConfig, RedisConfig, SecurityConfig,
                              VectorStoreConfig, get_config, get_database_url,
                              get_redis_url, is_debug, is_development,
                              is_production, reload_config)
from src.utils.errors import (AgentError, AgentOrchestrationError,
                              AIMasteryError, APIError, AuthenticationError,
                              CacheError, ChunkingError, ConfigurationError,
                              ContentModerationError, DatabaseError, DataError,
                              DataLoadingError, DataProcessingError,
                              DataValidationError, EmbeddingError,
                              ErrorContext, FineTuningError,
                              GuardrailViolation, InferenceError,
                              InfrastructureError, ModelError,
                              ModelLoadingError, QueryEnhancementError,
                              RAGError, RateLimitError, RerankingError,
                              RetrievalError, SafetyError, ToolExecutionError,
                              TrainingError, ValidationError, VectorStoreError,
                              format_error_for_api, get_error_chain,
                              is_retryable_error, raise_with_context)
from src.utils.logging import (ColoredFormatter, JSONFormatter,
                               SensitiveDataFilter, critical, debug, error,
                               get_logger, info, log_duration, log_performance,
                               log_request_response, warning)
from src.utils.types import (  # Basic types; Type variables; Protocols; Callables; Result types; Pagination; Performance; Strategy pattern; Builder pattern; Observer pattern; Repository pattern; Utility functions
    AsyncCallable, AsyncCallback, AsyncProcessor, AsyncTransformer, BatchIndex,
    BatchSize, Builder, CacheProtocol, Callback, ChunkerProtocol,
    ChunkProtocol, ChunkT, ComparableProtocol, ConfigDict, ConfigMapping,
    DistanceScore, DocumentProtocol, DocumentT, DurationMilliseconds,
    DurationSeconds, EmbeddingMatrix, EmbeddingModelProtocol, EmbeddingVector,
    Factory, IDType, K, LLMProtocol, MetadataDict, MetadataMapping, ModelT,
    Number, NumericArray, Observer, PageInfo, PaginatedResult, PathLike,
    PerformanceMetrics, Processor, Repository, RerankerProtocol, Result,
    RetrieverProtocol, ScoreType, SearchResultProtocol, SerializableProtocol,
    SimilarityScore, Strategy, Subject, SyncCallable, T, T_co, T_contra,
    TextLike, Timestamp, Transformer, V, Validator, VectorStoreProtocol,
    ensure_list, ensure_sequence, is_mapping, is_numeric, is_sequence)

__all__ = [
    # Logging
    "get_logger",
    "log_performance",
    "log_request_response",
    "log_duration",
    "debug",
    "info",
    "warning",
    "error",
    "critical",
    "ColoredFormatter",
    "JSONFormatter",
    "SensitiveDataFilter",
    # Errors
    "AIMasteryError",
    "RAGError",
    "ChunkingError",
    "EmbeddingError",
    "RetrievalError",
    "VectorStoreError",
    "RerankingError",
    "QueryEnhancementError",
    "ModelError",
    "TrainingError",
    "InferenceError",
    "FineTuningError",
    "ModelLoadingError",
    "ConfigurationError",
    "ValidationError",
    "DataError",
    "DataLoadingError",
    "DataProcessingError",
    "DataValidationError",
    "InfrastructureError",
    "DatabaseError",
    "CacheError",
    "APIError",
    "AuthenticationError",
    "RateLimitError",
    "AgentError",
    "ToolExecutionError",
    "AgentOrchestrationError",
    "SafetyError",
    "ContentModerationError",
    "GuardrailViolation",
    "raise_with_context",
    "is_retryable_error",
    "get_error_chain",
    "format_error_for_api",
    "ErrorContext",
    # Configuration
    "Config",
    "get_config",
    "reload_config",
    "get_database_url",
    "get_redis_url",
    "is_production",
    "is_development",
    "is_debug",
    "DatabaseConfig",
    "RedisConfig",
    "LLMConfig",
    "EmbeddingConfig",
    "VectorStoreConfig",
    "RAGConfig",
    "CacheConfig",
    "APIConfig",
    "MonitoringConfig",
    "SecurityConfig",
    # Types
    "Number",
    "NumericArray",
    "EmbeddingVector",
    "EmbeddingMatrix",
    "TextLike",
    "PathLike",
    "IDType",
    "ScoreType",
    "SimilarityScore",
    "DistanceScore",
    "BatchSize",
    "BatchIndex",
    "ConfigDict",
    "ConfigMapping",
    "MetadataDict",
    "MetadataMapping",
    "T",
    "K",
    "V",
    "T_co",
    "T_contra",
    "DocumentT",
    "ChunkT",
    "ModelT",
    "DocumentProtocol",
    "ChunkProtocol",
    "EmbeddingModelProtocol",
    "VectorStoreProtocol",
    "SearchResultProtocol",
    "ChunkerProtocol",
    "RetrieverProtocol",
    "RerankerProtocol",
    "LLMProtocol",
    "CacheProtocol",
    "SerializableProtocol",
    "ComparableProtocol",
    "SyncCallable",
    "AsyncCallable",
    "Processor",
    "AsyncProcessor",
    "Transformer",
    "AsyncTransformer",
    "Validator",
    "Factory",
    "Callback",
    "AsyncCallback",
    "Result",
    "PageInfo",
    "PaginatedResult",
    "PerformanceMetrics",
    "DurationSeconds",
    "DurationMilliseconds",
    "Timestamp",
    "Strategy",
    "Builder",
    "Observer",
    "Subject",
    "Repository",
    "is_numeric",
    "is_sequence",
    "is_mapping",
    "ensure_list",
    "ensure_sequence",
]
