"""
Utilities Module for AI-Mastery-2026
=====================================

Shared utilities used across all modules.

Submodules:
-----------
- logging: Unified logging configuration
- errors: Unified error handling
- config: Configuration management
- types: Shared type definitions

Usage:
------
    from src.utils import get_logger, get_config, AIMasteryError
    from src.utils.types import DocumentProtocol, EmbeddingVector
    
    logger = get_logger(__name__)
    config = get_config()
"""

from src.utils.logging import (
    get_logger,
    log_performance,
    log_request_response,
    log_duration,
    debug,
    info,
    warning,
    error,
    critical,
    ColoredFormatter,
    JSONFormatter,
    SensitiveDataFilter,
)

from src.utils.errors import (
    AIMasteryError,
    RAGError,
    ChunkingError,
    EmbeddingError,
    RetrievalError,
    VectorStoreError,
    RerankingError,
    QueryEnhancementError,
    ModelError,
    TrainingError,
    InferenceError,
    FineTuningError,
    ModelLoadingError,
    ConfigurationError,
    ValidationError,
    DataError,
    DataLoadingError,
    DataProcessingError,
    DataValidationError,
    InfrastructureError,
    DatabaseError,
    CacheError,
    APIError,
    AuthenticationError,
    RateLimitError,
    AgentError,
    ToolExecutionError,
    AgentOrchestrationError,
    SafetyError,
    ContentModerationError,
    GuardrailViolation,
    raise_with_context,
    is_retryable_error,
    get_error_chain,
    format_error_for_api,
    ErrorContext,
)

from src.utils.config import (
    Config,
    get_config,
    reload_config,
    get_database_url,
    get_redis_url,
    is_production,
    is_development,
    is_debug,
    DatabaseConfig,
    RedisConfig,
    LLMConfig,
    EmbeddingConfig,
    VectorStoreConfig,
    RAGConfig,
    CacheConfig,
    APIConfig,
    MonitoringConfig,
    SecurityConfig,
)

from src.utils.types import (
    # Basic types
    Number,
    NumericArray,
    EmbeddingVector,
    EmbeddingMatrix,
    TextLike,
    PathLike,
    IDType,
    ScoreType,
    SimilarityScore,
    DistanceScore,
    BatchSize,
    BatchIndex,
    ConfigDict,
    ConfigMapping,
    MetadataDict,
    MetadataMapping,
    # Type variables
    T,
    K,
    V,
    T_co,
    T_contra,
    DocumentT,
    ChunkT,
    ModelT,
    # Protocols
    DocumentProtocol,
    ChunkProtocol,
    EmbeddingModelProtocol,
    VectorStoreProtocol,
    SearchResultProtocol,
    ChunkerProtocol,
    RetrieverProtocol,
    RerankerProtocol,
    LLMProtocol,
    CacheProtocol,
    SerializableProtocol,
    ComparableProtocol,
    # Callables
    SyncCallable,
    AsyncCallable,
    Processor,
    AsyncProcessor,
    Transformer,
    AsyncTransformer,
    Validator,
    Factory,
    Callback,
    AsyncCallback,
    # Result types
    Result,
    # Pagination
    PageInfo,
    PaginatedResult,
    # Performance
    PerformanceMetrics,
    DurationSeconds,
    DurationMilliseconds,
    Timestamp,
    # Strategy pattern
    Strategy,
    # Builder pattern
    Builder,
    # Observer pattern
    Observer,
    Subject,
    # Repository pattern
    Repository,
    # Utility functions
    is_numeric,
    is_sequence,
    is_mapping,
    ensure_list,
    ensure_sequence,
)

__all__ = [
    # Logging
    "get_logger",
    "log_performance",
    "log_request_response",
    "log_duration",
    "debug",
    "info",
    "warning",
    "error",
    "critical",
    "ColoredFormatter",
    "JSONFormatter",
    "SensitiveDataFilter",
    # Errors
    "AIMasteryError",
    "RAGError",
    "ChunkingError",
    "EmbeddingError",
    "RetrievalError",
    "VectorStoreError",
    "RerankingError",
    "QueryEnhancementError",
    "ModelError",
    "TrainingError",
    "InferenceError",
    "FineTuningError",
    "ModelLoadingError",
    "ConfigurationError",
    "ValidationError",
    "DataError",
    "DataLoadingError",
    "DataProcessingError",
    "DataValidationError",
    "InfrastructureError",
    "DatabaseError",
    "CacheError",
    "APIError",
    "AuthenticationError",
    "RateLimitError",
    "AgentError",
    "ToolExecutionError",
    "AgentOrchestrationError",
    "SafetyError",
    "ContentModerationError",
    "GuardrailViolation",
    "raise_with_context",
    "is_retryable_error",
    "get_error_chain",
    "format_error_for_api",
    "ErrorContext",
    # Configuration
    "Config",
    "get_config",
    "reload_config",
    "get_database_url",
    "get_redis_url",
    "is_production",
    "is_development",
    "is_debug",
    "DatabaseConfig",
    "RedisConfig",
    "LLMConfig",
    "EmbeddingConfig",
    "VectorStoreConfig",
    "RAGConfig",
    "CacheConfig",
    "APIConfig",
    "MonitoringConfig",
    "SecurityConfig",
    # Types
    "Number",
    "NumericArray",
    "EmbeddingVector",
    "EmbeddingMatrix",
    "TextLike",
    "PathLike",
    "IDType",
    "ScoreType",
    "SimilarityScore",
    "DistanceScore",
    "BatchSize",
    "BatchIndex",
    "ConfigDict",
    "ConfigMapping",
    "MetadataDict",
    "MetadataMapping",
    "T",
    "K",
    "V",
    "T_co",
    "T_contra",
    "DocumentT",
    "ChunkT",
    "ModelT",
    "DocumentProtocol",
    "ChunkProtocol",
    "EmbeddingModelProtocol",
    "VectorStoreProtocol",
    "SearchResultProtocol",
    "ChunkerProtocol",
    "RetrieverProtocol",
    "RerankerProtocol",
    "LLMProtocol",
    "CacheProtocol",
    "SerializableProtocol",
    "ComparableProtocol",
    "SyncCallable",
    "AsyncCallable",
    "Processor",
    "AsyncProcessor",
    "Transformer",
    "AsyncTransformer",
    "Validator",
    "Factory",
    "Callback",
    "AsyncCallback",
    "Result",
    "PageInfo",
    "PaginatedResult",
    "PerformanceMetrics",
    "DurationSeconds",
    "DurationMilliseconds",
    "Timestamp",
    "Strategy",
    "Builder",
    "Observer",
    "Subject",
    "Repository",
    "is_numeric",
    "is_sequence",
    "is_mapping",
    "ensure_list",
    "ensure_sequence",
]
