"""
Domain Entities
================
Pure domain objects with no external dependencies.
These are the core building blocks of the RAG system.

كيانات المجال - كائنات نقية بدون تبعيات خارجية
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Sequence


# =============================================================================
# Value Objects / كائنات القيمة
# =============================================================================

@dataclass(frozen=True)
class TenantId:
    """
    Tenant identifier (typically user_id).
    Frozen to ensure immutability and hashability.
    
    معرف المستأجر - مجمد لضمان الثبات
    """
    value: str
    
    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True)
class DocumentId:
    """
    Document identifier (UUID string).
    
    معرف المستند
    """
    value: str
    
    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True)
class ChunkId:
    """
    Chunk identifier (UUID string).
    
    معرف القطعة
    """
    value: str
    
    def __str__(self) -> str:
        return self.value


# =============================================================================
# Domain Entities / كيانات المجال
# =============================================================================

@dataclass(frozen=True)
class StoredFile:
    """
    Represents a file that has been stored in the file system.
    
    يمثل ملفاً تم تخزينه في نظام الملفات
    """
    path: str
    filename: str
    content_type: str
    size_bytes: int


@dataclass(frozen=True)
class ExtractedText:
    """
    Result of text extraction from a document.
    
    نتيجة استخراج النص من مستند
    """
    text: str
    metadata: dict = field(default_factory=dict)


@dataclass(frozen=True)
class Chunk:
    """
    A chunk of text from a document with its metadata.
    
    Design Decision: Using frozen dataclass for:
    - Immutability (safe to pass around)
    - Hashability (can be used in sets/dicts)
    - Clear data structure
    
    قطعة نصية من مستند مع بياناتها الوصفية
    """
    id: str
    tenant_id: TenantId
    document_id: DocumentId
    text: str
    
    def __hash__(self) -> int:
        return hash(self.id)
    
    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Chunk):
            return NotImplemented
        return self.id == other.id


@dataclass(frozen=True)
class ChunkSpec:
    """
    Specification for chunking behavior.
    
    مواصفات سلوك التقطيع
    """
    max_tokens: int = 512
    overlap_tokens: int = 50
    encoding_name: str = "cl100k_base"


@dataclass(frozen=True)
class Answer:
    """
    An answer generated by the RAG system.
    
    إجابة منتجة من نظام RAG
    """
    text: str
    sources: Sequence[str]  # List of chunk IDs
    
    def __post_init__(self) -> None:
        # Ensure sources is a tuple for immutability
        if not isinstance(self.sources, tuple):
            object.__setattr__(self, "sources", tuple(self.sources))


@dataclass(frozen=True)
class UploadResult:
    """
    Result of a document upload operation.
    
    نتيجة عملية رفع مستند
    """
    document_id: DocumentId
    status: str  # "queued" | "already_exists" | "failed"
    message: str = ""


@dataclass
class DocumentStatus:
    """
    Current status of a document in the system.
    Not frozen because status changes over time.
    
    الحالة الحالية للمستند في النظام
    """
    document_id: DocumentId
    tenant_id: TenantId
    filename: str
    status: str  # "created" | "queued" | "processing" | "indexed" | "failed"
    error: str | None = None
    chunks_count: int = 0
    created_at: datetime | None = None
    updated_at: datetime | None = None


@dataclass
class ChatSession:
    """
    A chat session containing multiple turns.
    
    جلسة محادثة تحتوي على عدة دورات
    """
    id: str
    tenant_id: TenantId
    title: str | None = None
    created_at: datetime | None = None


@dataclass
class ChatTurn:
    """
    A single question-answer turn in a chat session.
    Includes observability fields for cost/latency tracking.
    
    دورة سؤال-جواب واحدة في جلسة محادثة
    """
    id: str
    session_id: str
    tenant_id: TenantId
    question: str
    answer: str
    sources: Sequence[str]
    retrieval_k: int = 0
    
    # Observability fields / حقول المراقبة
    embed_ms: int | None = None
    search_ms: int | None = None
    llm_ms: int | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    created_at: datetime | None = None
